/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DebtorRouteImport } from './routes/debtor'
import { Route as IndexRouteImport } from './routes/index'

const DebtorRoute = DebtorRouteImport.update({
  id: '/debtor',
  path: '/debtor',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/debtor': typeof DebtorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/debtor': typeof DebtorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/debtor': typeof DebtorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/debtor'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/debtor'
  id: '__root__' | '/' | '/debtor'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DebtorRoute: typeof DebtorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/debtor': {
      id: '/debtor'
      path: '/debtor'
      fullPath: '/debtor'
      preLoaderRoute: typeof DebtorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DebtorRoute: DebtorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
